### PR TITLE
Prepping for promotion.

### PR DESCRIPTION
**Pull request by nstielau**
@drnikki Once the survey is ready, I think you can tweet these out and update the `tweet_id`s for these recommended retweets, and we can send folks here.

### CODE REVIEW

**Comment by drnikko** [comment]
Awesome. I didn't see that copy had been finalize for those.  I'll be making the last of the question updates and changes late tonight/tomorrow in Berkeley and then will get them out.   Thanks!!!

**Comment by drnikko** [comment]
@nstielau I updated getfeedback this morning (still a little iffy on that language slide, but...???) and added in that last open-entry "what did we miss?" question. Look it over when you have a second and if it's good, I'll tweet it out today so we can update the readmes. 

very close very close.

**Comment by nstielau** [comment]
@drnikki What about changing "With which of the following languages do you have working proficiency?" to "Which of the following languages do you use in the workplace?"?  That makes it a little more focused on the act of building the web.

I also added a Net Promoter Score for the survey itself.  What do you think?

Also, can you double-check the 'required' questions? I think I made just about all of them required.

**Comment by drnikko** [comment]
@nstielau all are required (except for the last two, which I like) and overall I think we're ready.  I'll be at a venue early tomorrow morning, so if you're good, I'll get those tweets out then and update the readme.

**Pull request merged**
